# -*- coding: utf-8 -*-
"""count_freaquency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjbIMo1aBvuEFY1DS_w30tkUzVS3Y7ZQ
"""

def count_freaquency(nums):
  freq={}
  for num in nums:
    freq[num]= freq.get(num,0) +1
  return freq


nums=[1,3,2,2,1,2]
result=count_freaquency(nums)
print(result)

